//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancelindividual
    {
        public long ID { get; set; }
        public string TransportDetails { get; set; }
        public long ADID { get; set; }
        public long TransportDetailID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<System.DateTime> ManifestDate { get; set; }
        public string Session { get; set; }
        public string MenifestNo { get; set; }
        public string ADNO { get; set; }
        public string ArmyNo { get; set; }
        public Nullable<long> RankID { get; set; }
        public string Name { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string ICard { get; set; }
        public Nullable<long> HQID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
