//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class roommaster
    {
        public long Id { get; set; }
        public string RoomName { get; set; }
        public Nullable<long> BlockId { get; set; }
        public int MaxRoomCap { get; set; }
        public double RoomPrice { get; set; }
        public bool IsShare { get; set; }
        public Nullable<bool> IsBillShare { get; set; }
        public Nullable<bool> IsFull { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
