//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfercouriermaster
    {
        public long ID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Session { get; set; }
        public string ICardNo { get; set; }
        public string ArmyNo { get; set; }
        public Nullable<long> RankID { get; set; }
        public string Name { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> DivID { get; set; }
        public Nullable<long> HQID { get; set; }
        public string Authority { get; set; }
        public Nullable<long> MoveID { get; set; }
        public Nullable<long> PriorityID { get; set; }
        public Nullable<long> PriorityStatusID { get; set; }
        public Nullable<long> SeatNo { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string CharterNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
