//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class admaster
    {
        public long ID { get; set; }
        public string ADNO { get; set; }
        public string ReferenceN0 { get; set; }
        public string DocumentUrl { get; set; }
        public Nullable<long> BrigadeId { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string Session { get; set; }
        public string ICard { get; set; }
        public string ArmyNo { get; set; }
        public Nullable<long> RankID { get; set; }
        public string Name { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> DivID { get; set; }
        public Nullable<long> HQID { get; set; }
        public string Authority { get; set; }
        public Nullable<long> MoveID { get; set; }
        public Nullable<long> PriorityID { get; set; }
        public Nullable<bool> IsReserve { get; set; }
        public Nullable<bool> IsManifest { get; set; }
        public Nullable<bool> IsLoad { get; set; }
        public Nullable<long> AdTypeID { get; set; }
        public Nullable<long> BookingId { get; set; }
        public string BP { get; set; }
        public string FMN { get; set; }
        public string OnHoldRemark { get; set; }
        public string OnTempHoldRemark { get; set; }
        public Nullable<System.DateTime> LeaveFromDate { get; set; }
        public Nullable<System.DateTime> LeaveToDate { get; set; }
        public Nullable<int> LeaveNoOfDays { get; set; }
        public Nullable<int> NoOfAbsentDays { get; set; }
        public Nullable<bool> IsTempHold { get; set; }
        public Nullable<bool> IsPriority { get; set; }
        public Nullable<bool> IsOnHold { get; set; }
        public Nullable<bool> IsFly { get; set; }
        public Nullable<bool> IsLRC { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
