//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportdetail
    {
        public long ID { get; set; }
        public string TransportDetails { get; set; }
        public Nullable<long> TransportTypeID { get; set; }
        public string Session { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> TotalNoOfSeats { get; set; }
        public Nullable<long> NoOfSeats { get; set; }
        public Nullable<long> PrioritySeats { get; set; }
        public Nullable<long> Load { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
