//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermaster
    {
        public long ID { get; set; }
        public Nullable<long> UserRoleID { get; set; }
        public Nullable<long> ADID { get; set; }
        public string IDCardNo { get; set; }
        public string ArmyNumber { get; set; }
        public Nullable<long> RankID { get; set; }
        public Nullable<long> DivID { get; set; }
        public Nullable<long> HQID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Regiment { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
