using BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataLayer
{
    public interface IADServices
    {
        List<ADEntery> GetAllADLeft();
        List<ADEntery> GetAllADLeftModify();
        List<ADEntery> GetAllADLeft(Int64 cityID);
        ADEntery GetADNO(Int64 catId, Int64 city, string cityname);
        ADEntery GetADNO(string cityname, int catid);
        ADEntery GetByID(Int64 id);
        Int64 Update(ADEntery info);
        Int64 Insert(ADEntery info);
        List<ADEntery> Paging(Int32 take, Int32 skip);
        Int32 TotalItems();
        void Delete(Int64 ID);
        List<ADEntery> GetSearchResult(String SearchText);
        void Save();
        List<ADEntery> GetAllADsForRation(int cityid);
        List<ADEntery> GetAllADsForRationBF(int cityid);
        List<ADEntery> GetAllADsForRationDep(int cityid);
        List<ADEntery> ADEntryNo();
        ADEntery GetADNO(Int64 catId, Int64 city);
        string GetADNO();
        List<ADEntery> GetADDetails();
        void Reserve(Int64 ID);
        List<ADEntery> ADEntryNoPriority();
        List<ADEntery> ADEntryNoPriority(Int64 cityID);
        List<ADEntery> ADEntryNoPriorityCat(Int64 CatID);
        List<ADEntery> ADEntryNoGeneral();
        List<ADEntery> ADEntryNoGeneralCityWise(Int64 cityID);
        List<ADEntery> ADEntryNoGeneralCat(Int64 CatID);
        List<ADEntery> ADEntryNoReserve();
        List<ADEntery> ADEntryNoReserveCityWise(Int64 cityID);
        List<ADEntery> ADEntryNoReserveCat(Int64 CatID);
        List<ADEntery> PagingPriority(Int32 take, Int32 skip);
        List<ADEntery> PagingReserve(Int32 take, Int32 skip);
        List<ADEntery> PagingOnHold(Int32 take, Int32 skip);
        List<ADEntery> GetSearchResultReserve(String SearchText);
        List<ADEntery> GetSearchResultTempHold(String SearchText);
        List<ADEntery> GetSearchResultPriority(String SearchText);
        Int32 TotalItemsPriority();
        Int32 TotalItemsOnHoldStatus();
        Int32 TotalItemsOnTemHold();
        Int32 TotalItemsOnReserve();
        Int32 TotalItemsOnHold();
        List<ADEntery> PagingOnHoldFinal(Int32 take, Int32 skip);
        List<ADEntery> GetSearchResultOnHoldStatus(String SearchText);
        List<ADEntery> ADEntryNoPriorityCity(Int64 CityID);
        List<ADEntery> ADEntryNoGeneralCity(Int64 CityID);
        List<ADEntery> ADEntryNoReserveCity(Int64 CityID);
        List<ADEntery> GetByDate(DateTime datefrom, DateTime dateto);
        List<ADEntery> GetByDate(DateTime datefrom, DateTime dateto, int cid);
        List<ADEntery> GetByDate(DateTime today);
        List<ADEntery> GetByDate(DateTime today, int cid);
        Int32 TotalItemsLoad();
        List<ADEntery> PagingLoad(Int32 take, Int32 skip);
        List<ADEntery> GetSearchResultLoad(String SearchText);
        void Load(Int64 ID);
        List<ADEntery> ADEntryNoLoadCity(Int64 CityID);
        List<ADEntery> ADEntryNoLoad();
        List<ADEntery> ADEntryNoLoad(Int64 cityID);
        List<ADEntery> PagingOnHold();
        List<ADEntery> PagingOnHolding();
        List<ADEntery> MoveTypeWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> MoveTypeWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> CityWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> CityWiseReportdeparture(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> StatusWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> UnitWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> DivisionWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> DivisionWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> DepartureDateWiseReport(DateTime fromdate, DateTime todate);
        List<ADEntery> DepartureDateWiseReport(DateTime fromdate, DateTime todate, Int64 cityID);
        List<ADEntery> DepartureCityWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> DepartureMoveTypeWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> DepartureMoveTypeWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cID);
        List<ADEntery> DepartureUnitWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> DepartureUnitWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> DepartureDivisionWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> DepartureDivisionWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> HQWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> HQWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> DepartureWiseReport(DateTime fromdate, DateTime todate, Int64 id);
        List<ADEntery> DepartureWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> MoveTypeWiseReportByID(Int64 id, DateTime date);
        List<ADEntery> MoveTypeWiseReportByID(Int64 id, DateTime date, int cid);
        List<ADEntery> CityWiseReportID(Int64 id, DateTime date);
        List<ADEntery> CityWiseReportIDALL(Int64 id, DateTime date);
        List<ADEntery> CityWiseReportIDDeparture(Int64 id, DateTime date);
        List<ADEntery> StatusWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> UnitWiseReportID(Int64 id, DateTime date);
        List<ADEntery> UnitWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> DivisionWiseReportID(Int64 id, DateTime date);
        List<ADEntery> DivisionWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> HQWiseReportID(Int64 id, DateTime date);
        List<ADEntery> HQWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> DepartureCityWiseReportID(Int64 id, DateTime date);
        List<ADEntery> DepartureMoveTypeWiseReportID(Int64 id, DateTime date);
        List<ADEntery> DepartureMoveTypeWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> DepartureUnitWiseReportID(Int64 id, DateTime date);
        List<ADEntery> DepartureUnitWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> DepartureDivisionWiseReportID(Int64 id, DateTime date);
        List<ADEntery> DepartureDivisionWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> WaitingListReport(Int64 cityId, DateTime date);
        List<ADEntery> WaitingListReportMod(Int64 cityId, DateTime date);
        List<ADEntery> WaitingListReportMod(DateTime date);
        List<ADEntery> WaitingListReport(Int64 cityId, int unitid, DateTime date);
        List<ADEntery> WaitingListReportFMN(Int64 cityId, int divId, DateTime date);
        List<ADEntery> WaitingListReportMod(int cityID, DateTime date);
        List<ADEntery> WaitingListReport(Int64 cityId, DateTime fromdate, DateTime toDate);
        List<ADEntery> DepartureWiseReportID(Int64 id, DateTime date);
        List<ADEntery> DepartureWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> GetByDateForHoldingReport(DateTime date);
        List<ADEntery> GetByDateForHoldingReport(DateTime date, int cid);
        List<ADEntery> GetByDateForOnHoldingReport(DateTime date, int cid);
        List<ADEntery> GetByDateForHoldingReportDateRange(DateTime fromdate, DateTime todate, int cid);
        List<ADEntery> GetByDateForOnHoldingReportDateRange(DateTime fromdate, DateTime todate, int cid = 0);
        List<ADEntery> MedicalStatusWiseReport(DateTime fromdate, DateTime todate, Int64 id, int cid);
        List<ADEntery> MedicalStatusWiseReportID(Int64 id, DateTime date, int cid);
        List<ADEntery> DepartureDateWiseReport(DateTime date);
        List<ADEntery> DepartureDateWiseReport(DateTime date, int cityID);
    }
}
